### ISSUE TITLE
is there a way to call methods which return byte[] or char[] ?

### ISSUE THREAD

**Issue by bartes** [HipByte/RubyMotion#188]
I got crash all the time with:

unrecognized call return type `[B'

unrecognized call return type `[C'

Example in Android
"nice_string".toString().getBytes()

**Comment by TigerWolf** [comment]
Im having this problem too. I have created a ticket as well for this. #2719

**Comment by TigerWolf** [comment]
My current work around is to do all of my byte[] work in a .java file. For example:

```

public java.lang.String convertTo64(java.lang.String string) {
  return android.util.Base64.encodeToString(string.getBytes(),  android.util.Base64.NO_WRAP);
}
```

**Comment by MarkVillacampa** [comment]
A fix for this will be available in the next version of Rubymotion.

This repository is only for the open source part of the toolchain, please if you have any problem or feature request, file a `motion support`.

Thank you.
