### ISSUE TITLE
osx: REPL crash

### ISSUE THREAD

**Issue by bmichotte** [HipByte/RubyMotion#209]
Hi there,

not really sure if it's a RubyMotion bug or something in my app, but as soon as I type something in REPL for [HSTracker](https://github.com/bmichotte/HSTracker), the app crash.

How to reproduce 
- git clone
- bundle update
- rake update
- rake

in REPL, type something like "hello", then "tab" to switch back to the app -> crash

**Comment by MarkVillacampa** [comment]
Hi bmichotte,

This issue tracker is only for the open source part of the RM toolchain. For questions about the product and support requests for your app please file a "motion support" or ask in the community forums: http://community.rubymotion.com

Thanks,
Mark.
