### ISSUE TITLE
librubymotion-static duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by mbelnicoff** [HipByte/RubyMotion#217]
Build ./build/iPhoneOS-8.2-Development
      Link ./build/iPhoneOS-8.2-Development/XXXXX.app/XXXXX
duplicate symbol l059 in:
    /Library/RubyMotion/data/ios/8.2/iPhoneOS/librubymotion-static.a(bignum.o)
    /Library/RubyMotion/data/ios/8.2/iPhoneOS/librubymotion-static.a(math.o)
duplicate symbol l060 in:
    /Library/RubyMotion/data/ios/8.2/iPhoneOS/librubymotion-static.a(bignum.o)
    /Library/RubyMotion/data/ios/8.2/iPhoneOS/librubymotion-static.a(math.o)
duplicate symbol l061 in:
    /Library/RubyMotion/data/ios/8.2/iPhoneOS/librubymotion-static.a(bignum.o)
    /Library/RubyMotion/data/ios/8.2/iPhoneOS/librubymotion-static.a(math.o)
duplicate symbol l062 in:
    /Library/RubyMotion/data/ios/8.2/iPhoneOS/librubymotion-static.a(bignum.o)
    /Library/RubyMotion/data/ios/8.2/iPhoneOS/librubymotion-static.a(math.o)
duplicate symbol l061 in:
    /Library/RubyMotion/data/ios/8.2/iPhoneOS/librubymotion-static.a(bignum.o)
    /Library/RubyMotion/data/ios/8.2/iPhoneOS/librubymotion-static.a(rational.o)
duplicate symbol l064 in:
    /Library/RubyMotion/data/ios/8.2/iPhoneOS/librubymotion-static.a(enum.o)
    /Library/RubyMotion/data/ios/8.2/iPhoneOS/librubymotion-static.a(marshal.o)
ld: 6 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
rake aborted!

**Comment by jamonholmgren** [comment]
I'd recommend doing a `rake clean:all`. That usually fixes this issue for me.

If the recompile takes too long for you, try out my gem [compressor](https://github.com/jamonholmgren/compressor). It'll speed up your compiles in most cases.

**Comment by mbelnicoff** [comment]
I will tryit.
I have tryed with rake:clear and trying to rollback to differentes version of rubymotion without any lucky.
Then i found that librubymotion-static have this archictures:
lipo -info /Library/RubyMotion/data/ios/8.2/iPhoneOS/librubymotion-static.a
Architectures in the fat file: /Library/RubyMotion/data/ios/8.2/iPhoneOS/librubymotion-static.a are: armv7 armv7s (cputype (16777228) cpusubtype

I'm wondering if it is a good idea to exclude arm64 arch from my project.

**Comment by mbelnicoff** [comment]
Same result!!

**Comment by mbelnicoff** [comment]
Adding
app.archs['iPhoneOS'] |= ['armv7', 'armv7s']
to my rakefile
them clean and try to run rake:archive
Get the same error :( Not my day!

Any recommendation?

**Comment by mbelnicoff** [comment]
Finally I can avoid this issue upgrading to SDK 8.3.
