### ISSUE TITLE
Allow setting of bluetooth-peripheral in app.background_modes

### ISSUE THREAD

**Issue by sajoku** [HipByte/RubyMotion#219]
Wanting to create an iOS app with Bluetooth functionality I'm trying to set the background mode to bluetooth-peripheral. Doing a rake gives the following error:
```
ERROR! Unknown background_modes value: `bluetooth_peripheral'
```
I am not sure if it is as easy as adding a mapping from ```:bluetooth_peripheral``` to ```"bluetooth-peripheral"```. 

I am also not sure if this is just a convenience method and if I should be able to do something like ```App.config.info_plist['UIBackgroundModes'] += "bluetooth-peripheral"```? (which does not work).

Looking at  [config.rb#:354](https://github.com/HipByte/RubyMotion/blob/eca9916648372df66e2cd43596b790f5fbfa7c58/lib/motion/project/template/ios/config.rb#L354) it may be as easy as adding a new mapping to the correct string.

Looking up the allow background-modes I also noticed some other options are missing:

https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW22

``` fetch``` and ```remote-nofication```

1. How do I set the plist info to allow bluetooth-peripheral as background mode?
2. Would "you" like me to create a pull-request to allow all of the known background-modes as mappings? :smile: 

_edit:_
Tried some things and I think this should work:
```
app.info_plist['UIBackgroundModes'] = [ 'bluetooth-central', 'bluetooth-peripheral' ]
```

**Comment by colinta** [comment]
Yes, a pull-request would be welcomed!  Thanks!

**Comment by sajoku** [comment]
Haven't forgotten about this but just haven't gotten around to making these changes.
Hopefully I'll create a pull-request later this week / weekend.

**Comment by sajoku** [comment]
I created a pull request #221 :)
