### ISSUE TITLE
Info.plist values not get resolved like Xcode

### ISSUE THREAD

**Issue by siuying** [HipByte/RubyMotion#224]
On Xcode, we can define custom variable in info.plist:

```
<key>AppIdentifierPrefix</key>
<string>$(AppIdentifierPrefix)</string>
```

... and at compile time, Xcode will replace ``$(AppIdentifierPrefix)`` with proper value. It seems rubymotion compiler do not process the $ variable as Xcode, and only return the string ``"$(AppIdentifierPrefix)"``

**Comment by MarkVillacampa** [comment]
Hi @siuying

Can you post an example of a situation where this is needed?

RubyMotion generates all the info.plist manually, we do not use any plist generated by xcode.

**Comment by siuying** [comment]
I happens needs to access $(AppIdentifierPrefix) (Bundle Seed ID), which is needed to access keychain access group.

I figured out I could use app.seed_id in motion Rakefile, so I guess I dont need it now.
