### ISSUE TITLE
Can't initialize CLCircularRegion with initCircularRegionWithCenter

### ISSUE THREAD

**Issue by tbem** [HipByte/RubyMotion#225]
When i try to run CLCircularRegion.alloc.initCircularRegionWithCenter it it throw NoMethodError, but when i list CLCircularRegion methods beginning with init with tab the method is listed...

Any thoughts?

**Comment by colinta** [comment]
Can you share the code you wrote?  My guess is you're missing the extra parameters to this method.

```ruby
CLCircularRegion.alloc.initCircularRegionWithCenter([0, 0], radius: r, identifier: "whatever")
```

**Comment by colinta** [comment]
Actually let's use the forum for this discussion.

**Comment by tbem** [comment]
You're right, but anyway, if i try to do this on console this blocks the console, and the error message that i expected in the case of missing parameters should be missing parameters instead of no method. 
But i'm just a newbie in the rubymotion world so there are some issues that aren't clear for me yet.
Anyway thanks for your answer :+1:

**Comment by colinta** [comment]
-> forum please, so others can follow along.
