### ISSUE TITLE
Cannot build distribution archive with apostrophe in the app name 

### ISSUE THREAD

**Issue by BobaFaux** [HipByte/RubyMotion#229]
If I have an app name like "Woody's Pizza" (e.g. app.name = "Woodys Pizza" in the rake file) Ruby Motion works in all cased except for when you attempt to build an archive for distribution, then you get this error:

    /usr/bin/strip  './build/iPhoneOS-8.0-Release/Woody's Pizza.app/Woody's Pizza'
    error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip:   can't open file: ./build/iPhoneOS-8.0-Release/Woodys (No such file or directory)
    error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: can't open file: Pizza.app/Woodys Pizza (No such file or directory)
    rake aborted!
    Failed to execute: /usr/bin/strip  './build/iPhoneOS-8.0-Release/Woody's Pizza.app/Woody's Pizza'

If you remove the apostrophe then it works builds just fine.

**Comment by jjaffeux** [comment]
@BobaFaux Could you try with this solution please :

app.name = 'some_name'
app.info_plist['CFBundleDisplayName'] = "some’name"
