### ISSUE TITLE
can't create pointer required by bridgesupport

### ISSUE THREAD

**Issue by leemhenson** [HipByte/RubyMotion#230]
Hi.

I'm trying to use bridgesupport to access the following c library function:

```c
ZYRE_EXPORT int zyre_shout (zyre_t *self, const char *group, zmsg_t **msg_p);
```

Bridgesupport converts this into:

```xml
<function name='zyre_shout'>
<arg declared_type='zyre_t*' name='self' type='^{_zyre_t=}'/>
<arg const='true' declared_type='char*' name='group' type='*'/>
<arg declared_type='int**' name='msg_p' type='^^i'/>
<retval declared_type='int' type='i'/>
</function>
```

The `msg_p` arg at the end is defined as a pointer to an int pointer, `int**`. If I try to create a pointer like this:

```
Pointer.new('^i')
```

it crashes RubyMotion. Is it possible to call this function via bridgesupport?

Cheers
Lee

**Comment by Watson1978** [comment]
Thank you for report. 
There is same ticket in http://hipbyte.myjetbrains.com/youtrack/issue/RM-711
You can track the status with it.

So, I will close this ticket.

**Comment by leemhenson** [comment]
Hi Watson. Thanks for the link. On that page it says:

```
Fixed in build: Next Build
```

Does that mean 3.15 or 4.0? Is there an eta on that?

**Comment by jamonholmgren** [comment]
@leemhenson That's just the default for YouTrack. I wouldn't put much stock in it.
