### ISSUE TITLE
BigDecimal duplication : TypeError: can't copy Float

### ISSUE THREAD

**Issue by Infotaku** [HipByte/RubyMotion#239]
Hello,

I've just noticed that trying to duplicate a BigDecimal raises a TypeError.

```
(main)>BigDecimal.new('4.56').dup
2016-03-17 20:58:18.552 MyApplication[12480:4435183] can't copy Float (TypeError)
=> #<TypeError: can't copy Float>
```

I'm guessing by reading [this](http://www.rubymotion.com/news/2014/05/21/new-in-rubymotion-bigdecimal-better-localization.html) that it should not use Float anymore, am I guessing wrong ?

I'm using the iPhoneSimulator-9.2 with ruby 2.2.4

**Comment by Watson1978** [comment]
I filed the issue in http://hipbyte.myjetbrains.com/youtrack/issue/RM-1053
So, I will close this ticket.

Thank you for reporting.
