### ISSUE TITLE
About file order and the weirdly preferred unshift method.

### ISSUE THREAD

**Issue by Infotaku** [HipByte/RubyMotion#240]
Hi !

Can someone explain to me why the preferred method to add compilation files is to unshift them into the project files ?
I find it very weird since in order to use some gem I have to require them after my project setup in the Rakefile : 

```ruby
$:.unshift("/Library/RubyMotion/lib")

require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  app.name = 'MyApplication'
  app.files << Dir['lib/**/*.rb']
end

require 'some-gem-required-at-compilation-time'
```

I understand this comes from the fact that app/**/*.rb files are required by default when the first Motion::Project::App.setup block is executed, and that we therefore need to unshift all other dependencies before these auto-loaded files. But isn't that counter-intuitive ?
I mean, in a common Ruby project, we require our dependencies in the order we want them to load :

```ruby
require 'file1'
require 'file2-that-needs-file1'
```

but in a RubyMotion project, since the preferred way to add files is to unshift them, we actually have to do (in Rakefile) : 

```ruby
Motion::Project::App.setup do |app|
  # assuming file2 is required to compile files under "app/"
end
require 'file-that-unshift-file2-into-project-files'
require 'file-that-unshift-file1-into-project-files'
```

Am I missing something obvious that completely justify doing this ? 
Or maybe am I just too picky ? :stuck_out_tongue:

**Comment by colinta** [comment]
You're saying "unshift", but then using the << (push / concat) operator. I unshifting the lib/ folder would actually accomplish what you want, because the lib files would be at the beginning of the files array.

Or you can use the app.files_dependencies (or is it file_dependencies? I don't recall), which will guarantee file order regardless of how they are ordered in app.files.

**Comment by Infotaku** [comment]
My mistake sorry, I really meant app.files.unshift Dir['lib/**/*.rb'], but that was not the point, I shouldn't have put the lib folder in the example.

Let me explain with the full story that lead me to this post :

I recently implemented RubyMotion support into [AASM](https://github.com/aasm/aasm).
Since I really like that gem, I also decided to give it full support for [CDQ](https://github.com/infinitered/cdq), just like it already supports other Ruby ORMs like ActiveRecord.
To do that, I had to implement the `after_initialize` callback into CDQ, what I could easily do with the [motion-support](https://github.com/rubymotion/motion-support) gem by simply doing 

```ruby
class CDQManagedObject < CoreDataQueryManagedObjectBase
  include MotionSupport::Callbacks
```

and then calling `define_callbacks`, `set_callback` and `run_callbacks` where it makes sence.
I added motion-support to CDQ's list of required gems

```ruby
gem.add_dependency 'motion-support', '~> 0.3.0'
```

and I thought this was over. I ran CDQ's specs and boom : `uninitialized constant CDQManagedObject::MotionSupport`.

I tried adding `require 'motion-support'` all over the place, but no success. So I looked at [motion-support](https://github.com/rubymotion/motion-support)'s sources to find that it was using [motion-require](https://github.com/clayallsopp/motion-require). 
Convinced that was the source of the issue, I have redone all there file requirements, unshifting everything and meticulously setting all file dependencies with RubyMotion's `app.files_dependencies` method. 
You can look at the new files [here](https://github.com/Infotaku/motion-support/tree/master/lib), I just pushed them to my fork.

Aaaaaand now I look like an idiot... 
I was testing everything I was putting in this post and it just worked like a fucking charm O_O, I can even put the `require 'motion-support/callbacks'` before OR after CDQ's own file requirements... 
I am a hundred percent sure it was not working yesterday, or maybe I was just too tired to see what I was doing wrong. 
I'm guessing this has something to do with RubyMotion's `app.detect_dependencies` that was somehow not working because of [motion-require](https://github.com/clayallsopp/motion-require). 
Let's hope this continues to work once my pull requests get merged.

That being said, with `app.detect_dependencies = false`, I still need to put the `require 'motion-support/callbacks'` **after** CDQ's `Motion::Project::App.setup` block or the build will fail at 
```ruby
class CDQManagedObject < CoreDataQueryManagedObjectBase
  include MotionSupport::Callbacks
```

I guess that was the point I was trying to make. Requiring "files" after the project setup block seems a bit weird to me.

**Comment by MarkVillacampa** [comment]
It does not matter where you put the `require` (in fact, it should be better to just declare your dependencies in the Gemfile and let bundler automatically load them). Then when you run `rake`, the RubyMotion build system will take all your files in `app.files` and compile them in the correct order taking into account their dependencies.

If you find this to *not* be the case, I would be very interested in taking a look at a test project that reproduces the issue :).
